### PR TITLE
[WIP] Switch to biblatex for Bibliography

### PR DESCRIPTION
**Pull request by koppor**
This PR is an initial shot for BibLaTeX support. **Everyone wanting to continue working on that - feel free. For our next conference, we will stick with bibtex**

## Issues to be solved
- [x] ":" After authors - e.g., in in proceedings
- [x] Add comma before "Hrsg." (LNI is not consistent here, but comma should be added)
- [x] "and others" from the bibliography is not printed
- [x] "(besucht am X)" should be ", Stand: X"
- [x] One letter too much if only one author shown (Az09 vs. Azu+09; Gl09 vs. Glu09)
- [x] Label for more than 3 names should be first firstname, not first three names -> Wa instead of WFE+ for Wasser, Feuer, Erde, Licht

## Word Template

This is the requirement by LNI. The biblatex style has to produce the contents like here. No excuses. Unfortunately.

[AB00]	Abel, K.; Bibel, U.: Formatierungsrichtlinien für Tagungsbände. Format-Verlag, Bonn, 2000.
[ABC01]	Abraham, N.; Bibel, U.: Corleone, P.: Formatting Contributions for Proceedings. In (Glück, H.I. Hrsg.): Proc. 7th Int. Conf. on Formatting of Workshop-Proceedings, New York 1999. Noah & Sons, San Francisco, S. 46-53, 2001.
[An14] 	Anteil an Frauen in der Informatik. Statistics Worldwide, 2014.
[Az09]	Azubi, L. et.al.: Die Fußnote in LNI-Bänden. In (Glück, H. I., Hrsg.): Formatierung 2009. LNI 999, Format-Verlag, Bonn, S. 135-162, 2009.
[Ez10]	Ezgarani, O.: The Magic Format – Your Way to Pretty Books. Noah & Sons, 2010.
[GI14]	GI, Gesellschaft für Informatik e.V., www.gi-ev.at, Stand: 24.12.2014.
[Gl09]	Glück, H. I.: Formatierung leicht gemacht. Formatierungsjournal 11/09, S. 23-27, 2009.
[Wa14a] 	Wasser, K.; Feuer, H.; Erde, R.; Licht, H.: Essenzen der Informatik. Verlag Formvoll, 2014.
[Wa14b] 	Wasser, K.; Feuer, H.; Erde, R.; Licht, H.: Ganz neue Essenzen der Informatik im selben Jahr. Format-Verlag, 2014.

## Current State

[AB00] Abel, K.; Bibel, U.: Formatierungsrichtlinien für Tagungsbände. Format-
Verlag, Bonn, 2000.
[ABC01] Abraham, N.; Bibel, U.; Corleone, P.: Formatting Contributions for Pro-
ceedings. In (Glück, H. I., ed.): Proc. 7th Int. Conf. on Formatting of
Workshop-Proceedings. Noah & Sons, San Francisco, pp. 46–53, 2001.
[An14] Anteil an Frauen in der Informatik, Statistics Worldwide, 2014.
[Azu+09] Azubi, L. et al.: Die Fußnote in LNI-Bänden. In (Glück, H. I., ed.): For-
matierung 2009, LNI 999, Format-Verlag, Bonn, pp. 135–162, 2009.
[Ezg10] Ezgarani, O.: The Magic Format – Your Way to Pretty Books. Noah &
Sons, 2010.
[GI14] Gesellschaft für Informatik e.V., 2014, url: http://www.gi-ev.de, visited
on: 12/24/2014.
[Glü01] Glück, H. I., ed., Proc. 7th Int. Conf. on Formatting of Workshop-Proceedings,
San Francisco: Noah & Sons, 2001.
[Glü09a] Glück, H. I., ed.: Formatierung 2009. Format-Verlag, Bonn, 2009.
[Glü09b] Glück, H. I.: Formatierung leicht gemacht. Formatierungsjournal 11/09,
pp. 23–27, 2009.
[Was+14a] Wasser, K.; Feuer, H.; Erde, R.; Licht, H.: Essenzen der Informatik. Verlag
Formvoll, 2014.
[Was+14b] Wasser, K.; Feuer, H.; Erde, R.; Licht, H.: Ganz neue Essenzen der Infor-
matik im selben Jahr. Format-Verlag, 2014.

### CODE REVIEW

**Comment by koppor** [comment]
Update: @LukasCBossert provided an alternative solution at https://github.com/LukasCBossert/LNI. I'm trying to integrate it in the current template.

**Comment by LukasCBossert** [comment]
With the commits by @georgd (https://github.com/LukasCBossert/LNI/commit/d30c096ba5027201d57b383f3c0f7416e3c259bc) it seems to work properly now. https://github.com/LukasCBossert/LNI

**Comment by koppor** [comment]
I try to merge @georgd's changes in. Currently, I cannot compile his source because of an issue with `family_i`

    Package xkeyval Error: `family_i' undefined in families `blx@opt@namepart'.

**Comment by LukasCBossert** [comment]
it worked fine with my system. is your biblatex/biber uptodate?

**Comment by georgd** [comment]
That’s weird. Biblatex v3.5 removed the underscores from family_i etc.

**Comment by koppor** [comment]
After a merge, it works. I updated the TODOs. Only four left, whereby the two first open should be easy to fix.

**Comment by koppor** [comment]
Note that I created `LNI-test-en.tex` and `LNI-test-de.tex` to enable a quick test for both languages. Currently, I'm testing with `LNI-test-en.tex`.

**Comment by LukasCBossert** [comment]
I just did some simplifications on the code - see my latest commit.

**Comment by LukasCBossert** [comment]
Arent all TODOs solved? I dont see anything missing, besides, I dont know what you mean with the first one.

**Comment by georgd** [comment]
@koppor they should all be fixed. Have you rerun biber?

**Comment by koppor** [comment]
I'm testing your branch. Added `\usepackage[utf8]{inputenc}` to be able to omit the biber warnings. 🎉 - yeah, only one issue remaining.

grabbed_20161007-162656

**Comment by georgd** [comment]
I don’t see it. There’s a period in both, the word template and your comment.

**Comment by koppor** [comment]
Yeah, deleting *.bbl and running biber again also solved the labeling issues 🎉

**Comment by koppor** [comment]
Oh, wow, yes. You are right.

OK, I'll integrate in the template.

**Comment by LukasCBossert** [comment]
Sorry, I dont see the error? I compile with XeLaTeX, that why I omit `\usepackage[utf8]{inputenc}`.

You can add 
```
\ExecuteBibliographyOptions{%
  sortcites     = true,
  giveninits    = true,
  useprefix     = false,
    bibencoding=utf8,%<<--- new
  maxbibnames   = 99,
  maxcitenames  = 3,
  eprint        = true,
  url           = true,
  doi           = false,
  isbn          = true,
  backref       = false
}
```

**Comment by koppor** [comment]
I'm using the old-school pdflatex as my current state is that microtype is fully supported by xelatex (source: http://tex.stackexchange.com/a/118926/9075). 😇

**Comment by LukasCBossert** [comment]
well, microtype is for my purpose well enough supported by xelatex. i dont see the difference to pdflatex then.

**Comment by koppor** [comment]
I just love the "Grauwertkorrektur" achieved by the "Font Expansion" thing. I also tried lualatex, but that did not work out either with my hundreds of used packages. Will investigate at another time. Maybe together at some [Dante event](https://www.dante.de/events.html).

**Comment by georgd** [comment]
One issue I see now: a comma instead of a colon after the editor in Gl01. Needs to be fixed with \DeclareDelimFormat[bib]{nametitledelim}{\nametitledelim}

**Pull request merged**
